#!/usr/bin/env bash
# CloudSecure Assessment Platform - Infrastructure Deployment
# Usage: ./deploy.sh
# This script deploys CloudSecure infrastructure to your AWS account.
set -euo pipefail

# ─── Colors & Helpers ──────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

info()  { echo -e "${CYAN}▸${NC} $*"; }
ok()    { echo -e "${GREEN}✓${NC} $*"; }
warn()  { echo -e "${YELLOW}⚠${NC} $*"; }
fail()  { echo -e "${RED}✗${NC} $*"; exit 1; }

# ─── Banner ────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║       CloudSecure Assessment Platform        ║${NC}"
echo -e "${BOLD}║        Infrastructure Deployment             ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════╝${NC}"
echo ""

# ─── Phase 1: Check Prerequisites ─────────────────────────────
echo -e "${BOLD}Phase 1: Checking prerequisites${NC}"
echo ""

# AWS CLI
if command -v aws >/dev/null 2>&1; then
  ok "AWS CLI $(aws --version 2>&1 | awk '{print $1}' | cut -d/ -f2)"
else
  fail "AWS CLI not found. Install: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
fi

# Node.js
NODE_BIN=""
if command -v node >/dev/null 2>&1; then
  NODE_BIN="node"
elif [ -d "${HOME}/.nvm/versions/node" ]; then
  # Find latest nvm-managed Node
  NODE_DIR=$(find "${HOME}/.nvm/versions/node" -maxdepth 1 -type d | sort -V | tail -1)
  if [ -x "${NODE_DIR}/bin/node" ]; then
    export PATH="${NODE_DIR}/bin:${PATH}"
    NODE_BIN="${NODE_DIR}/bin/node"
  fi
fi

if [ -n "$NODE_BIN" ]; then
  ok "Node.js $($NODE_BIN --version)"
else
  fail "Node.js not found. Install: https://nodejs.org/ (v18+ required)"
fi

# npm/npx
NPX_BIN=""
if command -v npx >/dev/null 2>&1; then
  NPX_BIN="npx"
elif [ -n "$NODE_BIN" ]; then
  NPX_DIR=$(dirname "$NODE_BIN")
  if [ -x "${NPX_DIR}/npx" ]; then
    NPX_BIN="${NPX_DIR}/npx"
  fi
fi
[ -n "$NPX_BIN" ] && ok "npx available" || fail "npx not found"

# Python
if command -v python3 >/dev/null 2>&1; then
  ok "Python $(python3 --version 2>&1 | awk '{print $2}')"
else
  fail "Python 3 not found. Install: https://www.python.org/downloads/"
fi

# pip
if python3 -m pip --version >/dev/null 2>&1; then
  ok "pip available"
else
  fail "pip not found. Install: python3 -m ensurepip"
fi

# Docker (optional)
HAS_DOCKER=false
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  ok "Docker $(docker --version | awk '{print $3}' | tr -d ',')"
  HAS_DOCKER=true
else
  warn "Docker not available — Prowler scanner will be skipped"
fi

echo ""

# ─── Phase 2: Configuration ───────────────────────────────────
echo -e "${BOLD}Phase 2: Configuration${NC}"
echo ""

# List available AWS profiles
PROFILES=$(aws configure list-profiles 2>/dev/null || echo "default")
info "Available AWS profiles:"
echo "$PROFILES" | while read -r p; do echo "    $p"; done
echo ""

# AWS Profile
read -rp "AWS profile to use [default]: " AWS_PROFILE
AWS_PROFILE=${AWS_PROFILE:-default}

# Validate credentials
info "Validating AWS credentials for profile '${AWS_PROFILE}'..."
CALLER_IDENTITY=$(aws sts get-caller-identity --profile "$AWS_PROFILE" --output json 2>/dev/null) || \
  fail "Cannot authenticate with profile '${AWS_PROFILE}'. Run: aws configure --profile ${AWS_PROFILE}"

ACCOUNT_ID=$(echo "$CALLER_IDENTITY" | python3 -c "import sys,json; print(json.load(sys.stdin)['Account'])")
CALLER_ARN=$(echo "$CALLER_IDENTITY" | python3 -c "import sys,json; print(json.load(sys.stdin)['Arn'])")
ok "Authenticated: account ${ACCOUNT_ID} (${CALLER_ARN})"

# Region
read -rp "AWS region [eu-west-1]: " AWS_REGION
AWS_REGION=${AWS_REGION:-eu-west-1}

# Environment
read -rp "Environment name (dev/test/prod) [dev]: " CLOUDSECURE_ENV
CLOUDSECURE_ENV=${CLOUDSECURE_ENV:-dev}

# Prowler
SKIP_PROWLER=false
PROWLER_IMAGE="carlosinfantes/cloudsecure-prowler:latest"
if [ "$HAS_DOCKER" = false ]; then
  SKIP_PROWLER=true
else
  echo ""
  read -rp "Include Prowler CIS scanner? (requires Docker) [Y/n]: " INCLUDE_PROWLER
  INCLUDE_PROWLER=$(echo "$INCLUDE_PROWLER" | tr '[:upper:]' '[:lower:]')
  if [[ "$INCLUDE_PROWLER" == "n" ]]; then
    SKIP_PROWLER=true
  fi
fi

# Save .env
cat > .env << EOF
# CloudSecure - Generated by deploy.sh on $(date +%Y-%m-%d)
AWS_PROFILE=${AWS_PROFILE}
AWS_REGION=${AWS_REGION}
CLOUDSECURE_ENV=${CLOUDSECURE_ENV}
PROWLER_IMAGE=${PROWLER_IMAGE}
SKIP_PROWLER=${SKIP_PROWLER}
EOF

ok "Configuration saved to .env"
echo ""

# ─── Phase 3: API Gateway CloudWatch Role ─────────────────────
echo -e "${BOLD}Phase 3: Setting up API Gateway logging${NC}"
echo ""

# Check if API Gateway account already has a CloudWatch role
APIGW_ROLE=$(aws apigateway get-account --profile "$AWS_PROFILE" --region "$AWS_REGION" \
  --query 'cloudwatchRoleArn' --output text 2>/dev/null || echo "None")

if [ "$APIGW_ROLE" = "None" ] || [ -z "$APIGW_ROLE" ]; then
  info "Creating CloudWatch role for API Gateway..."
  TRUST_POLICY='{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"apigateway.amazonaws.com"},"Action":"sts:AssumeRole"}]}'

  ROLE_ARN=$(aws iam create-role \
    --role-name APIGatewayCloudWatchRole \
    --assume-role-policy-document "$TRUST_POLICY" \
    --profile "$AWS_PROFILE" \
    --query 'Role.Arn' --output text 2>/dev/null) || \
    ROLE_ARN=$(aws iam get-role \
      --role-name APIGatewayCloudWatchRole \
      --profile "$AWS_PROFILE" \
      --query 'Role.Arn' --output text 2>/dev/null)

  aws iam attach-role-policy \
    --role-name APIGatewayCloudWatchRole \
    --policy-arn "arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs" \
    --profile "$AWS_PROFILE" 2>/dev/null || true

  # Wait for IAM propagation
  info "Waiting for IAM role propagation..."
  sleep 10

  aws apigateway update-account \
    --patch-operations op=replace,path=/cloudwatchRoleArn,value="$ROLE_ARN" \
    --profile "$AWS_PROFILE" --region "$AWS_REGION" >/dev/null

  ok "API Gateway CloudWatch logging configured"
else
  ok "API Gateway CloudWatch role already configured"
fi

echo ""

# ─── Phase 4: CDK Bootstrap ───────────────────────────────────
echo -e "${BOLD}Phase 4: Bootstrapping CDK${NC}"
echo ""

info "Running CDK bootstrap (idempotent)..."
cd infrastructure
npm ci --silent 2>/dev/null
$NPX_BIN cdk bootstrap "aws://${ACCOUNT_ID}/${AWS_REGION}" \
  --profile "$AWS_PROFILE" 2>&1 | tail -3
cd ..
ok "CDK bootstrapped"
echo ""

# ─── Phase 5: Build & Deploy ──────────────────────────────────
echo -e "${BOLD}Phase 5: Building and deploying${NC}"
echo ""

info "Installing dependencies..."
make install

info "Building Lambda layer..."
make layer

if [ "$SKIP_PROWLER" = false ]; then
  info "Setting up Prowler container image..."
  make prowler-push
else
  warn "Skipping Prowler setup (SKIP_PROWLER=true)"
fi

info "Deploying CloudSecure stacks..."
make deploy

echo ""
ok "Deployment complete!"
echo ""

# ─── Summary ──────────────────────────────────────────────────
echo -e "${BOLD}════════════════════════════════════════════════${NC}"
echo -e "${BOLD}  CloudSecure deployed successfully!${NC}"
echo -e "${BOLD}════════════════════════════════════════════════${NC}"
echo ""

# Retrieve API endpoint
API_ENDPOINT=$(aws cloudformation describe-stacks \
  --profile "$AWS_PROFILE" --region "$AWS_REGION" \
  --stack-name "CloudSecure-API-${CLOUDSECURE_ENV}" \
  --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" \
  --output text 2>/dev/null || echo "")

if [ -n "$API_ENDPOINT" ]; then
  echo -e "  API Endpoint:  ${CYAN}${API_ENDPOINT}${NC}"
  echo -e "  Health Check:  ${CYAN}${API_ENDPOINT}health${NC}"
fi

echo -e "  Account:       ${ACCOUNT_ID}"
echo -e "  Region:        ${AWS_REGION}"
echo -e "  Environment:   ${CLOUDSECURE_ENV}"
echo -e "  Prowler:       $([ "$SKIP_PROWLER" = true ] && echo 'skipped' || echo 'enabled')"
echo ""
echo -e "${BOLD}Next steps:${NC}"
echo "  1. Create an assessment role in the target account:"
echo "     aws cloudformation deploy --template-file onboarding/cloudformation/cloudsecure-role.yaml \\"
echo "       --stack-name CloudSecure-AssessmentRole --capabilities CAPABILITY_NAMED_IAM \\"
echo "       --parameter-overrides ExternalId=<your-external-id>"
echo ""
echo "  2. Install the CLI tool:"
echo "     pip install cloudsecure"
echo ""
echo "  3. Run your first assessment:"
echo "     cloudsecure assess --account-id <TARGET_ACCOUNT> --role-arn <ROLE_ARN> --external-id <EXTERNAL_ID>"
echo ""
